
#*** Bismark methylation extractor version v0.20.1 ***
````
cd /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline
ls methyl_extractor/ |sed s'#\(.*\)#ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/\1/\1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/\1#' >methyl_extractor.sh

ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/12-P1/12-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/12-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/12-P2/12-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/12-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/12-P3/12-P3_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/12-P3
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/13-P1/13-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/13-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/13-P2/13-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/13-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/13-P3/13-P3_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/13-P3
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/1-P1/1-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/1-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/1-P2/1-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/1-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P1/21-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P17/21-P17_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P17
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P19/21-P19_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P19
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P22/21-P22_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P22
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P3/21-P3_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P3
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P32/21-P32_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P32
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P34/21-P34_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P34
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P37/21-P37_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P37
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/21-P6/21-P6_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/21-P6
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/2-P1/2-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/2-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/2-P2/2-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/2-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/BE-P1/BE-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/BE-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/BE-P2/BE-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/BE-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/BE-P3/BE-P3_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/BE-P3
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/GE-P1/GE-P1_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/GE-P1
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/GE-P2/GE-P2_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/GE-P2
ts /usr/local/Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --ample_memory --multicore 4 --genome_folder /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/ftp.solgenomics.net/genomes/Solanum_lycopersicum/assembly/build_3.00 --report /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/bismark_deduplicate/GE-P3/GE-P3_1_val_1_bismark_bt2_pe.deduplicated.bam -o /data5/F15FTSUSAT0747_TOMrcwM/YXD_Bismark_pipeline/methyl_extractor/GE-P3
```
